language: python
python:
  - "3.4"
  - "3.5"
  - "3.6"
  - "3.7"
# command to install dependencies
install: "pip install -q -r requirements.txt"
# command to run tests
script: python setup.py test/test_app.py
